[WIP] Jekyll
UbuntuCZ/ubuntu-cz pull request #2
Opened 2018-11-25 17:33 UTC by MikkCZ

fix #1 

- [x] závislosti, pluginy, konfigurace
- [x] sestavení na Travis CI
- [x] template bez PHP
- [ ] obsah bez PHP
- [x] URL adresy stránek a přesměrování
- [x] readme
- [x] menu bez PHP
- [ ] vzdálený obsah bez PHP
- [ ] finální Travis CI pro `master`

2018-11-25 17:38 UTC, MikkCZ commented
Zatím jen jako náhled změn při přepisu na Jekyll do kompletně statické varianty. Trochu PHP ještě zbývá. ;)

2018-12-05 12:45 UTC, MikkCZ commented
@zubozrout můžu tě poprosit o review změn? K náhledu na https://mikkcz.github.io/iubuntu-cz/. Obsah by měl být beze změny, jen jsem PHP nahradil Jekyllem.

2018-12-05 19:12 UTC, zubozrout commented
@MikkCZ Vypadá to super ;), skvělá práce. Za mě jen snad tohle:
Validátor trochu nadává, něco se mu nelíbí: https://validator.w3.org/nu/?doc=https%3A%2F%2Fmikkcz.github.io%2Fiubuntu-cz%2F (vypadá to na překlepy v header menu)

Potom jsou trochu rozbité JS věci, ale když jsi na to nesahal, tak to dává smysl. Jinak doufám, že jsem nic nepřehlídl.

2018-12-05 19:13 UTC, zubozrout requested changes
Vypadá to super ;), skvělá práce. Za mě jen snad tohle:
Validátor trochu nadává, něco se mu nelíbí: https://validator.w3.org/nu/?doc=https%3A%2F%2Fmikkcz.github.io%2Fiubuntu-cz%2F (vypadá to na překlepy v header menu)

Potom jsou trochu rozbité JS věci, ale když jsi na to nesahal, tak to dává smysl. Jinak doufám, že jsem nic nepřehlídl.

2018-12-06 06:59 UTC, MikkCZ commented
Díky, validaci opravím.

Co z JS je rozbité? Já jsem si akorát na jednom počítači všiml, že zůstávají v angličtině položky z feedu, to je ono? To by se mělo opravit.

2018-12-06 07:12 UTC, zubozrout commented
@MikkCZ Tam je problém pak v tom, že spouštíš prohlížeč nejspíše s anglickým lokálem :). To je situace, kdy se překladač nespustí. Když to spustíš mimo anglický lokál, tak se to bude snažit přeložit do češtiny - a to mu nejde proto, že se mu nenačte slovník - špatná url, hrabe totiž o level výš: https://mikkcz.github.io/design/translator/data.json. Ale je to takový překladač nepřekladač, takže to možná není ani na škodu kdyby se nespustil nikdy.

Druhá věc jsou download button pro server/desktop, např. tady: https://mikkcz.github.io/iubuntu-cz/ziskat-ubuntu/stahnout-desktop/

Smazal jsi z tama JS, který fetchoval generované JSONy - jestli se nepletu, tak [tady](https://github.com/MikkCZ/iubuntu-cz/pull/2/commits/3d6ec4b34fda99a9a28c48970f636a89bb27437c#diff-10f724cf5f52f70339b23b1760c0111fL123).

Nicméně je otázka, nakolik to má být řešené tímto způsobem. Ty tlačítka bych si dokázal představit bez JS, byla by to dost možná lepší alternativa, ale vlastně nevím. Googlu, případně jiným search enginům, to může být ukradené a pro ty, co JS nemají, je tam backend fallback, který uživatele přesměruje přímo na tu stránku, ze které se ta data získávají (alespoň u LTS, u standard releasu aspoň běžně další vydání s jiným označením nebývají).

2018-12-06 07:16 UTC, zubozrout commented
Ale stejně mě děsí, že se tam nic nezobrazí. Teď se tomu nemůžu moc věnovat, ale v tom překladači je nějaká chyba - snažil jsem se to napsat tak, aby se vlastně nic nedělo, když není slovník, nebo to stáhne nějaký nesmysl, ale zjevně jsem to neotestoval a něco je tam špatně.

2018-12-06 07:28 UTC, MikkCZ commented
> a to mu nejde proto, že se mu nenačte slovník - špatná url, hrabe totiž o level výš: https://mikkcz.github.io/design/translator/data.json.

Ten JSON by měly být jednoduchá oprava, díky za tip.

> Druhá věc jsou download button pro server/desktop, např. tady: https://mikkcz.github.io/iubuntu-cz/ziskat-ubuntu/stahnout-desktop/
Smazal jsi z tama JS, který fetchoval generované JSONy - jestli se nepletu, tak tady.

Teď je to řešené tak, že si v době sestavení (např. jednou denně cronem) Jekyll stáhne aktuální verzi Ubuntu a tu verzi tam rovnou doplní. Co tam vidím za chybu je tlačítko pro LTS, které nevede přímo na ISO (chyba, opravit) a info o verzi a velikosti ne-LTS souboru. To nevím, jestli tam mít nebo nemít, ale taky by se to asi dalo stahovat.

2018-12-06 07:34 UTC, zubozrout commented
@MikkCZ "info o verzi a velikosti" - jo, tohle asi klidně vynechat. Nemyslím si, že je to tak důležité. Sice by někoho mohlo zajímat, kolik toho vlastně bude stahovat a jestli si na mobilním připojení třeba neprotočí FUP :), ale ani oficiální web to neuvádí.

2018-12-06 18:44 UTC, MikkCZ commented
@zubozrout tak už je snad vše opraveno, viz výše. Jen ten HTML validátor to nějak nevidí, ale když mu vložím přímo HTML co dostanu, tak je až na chybějící nadpisy v `<section>` (sémantika HTML5) spokojený.

2018-12-06 20:44 UTC, zubozrout commented
@MikkCZ To bude nějaká cache, mně to validátor zobrazuje dobře. Ty sémantické chyby jsem tam bohužel měl, ale nějak se mi používaní `<section>` v době, kdy jsem to psal, strašně líbilo. Tak to tam je takhle. A pořád mi přijde být použití section v tomhle kontextu ok, ale co já vím :).
Každopádně díky moc, že jsi to vyřešil, a klobouk dolů, že tak rychle ;).

2018-12-07 08:33 UTC, MikkCZ commented
Díky za review. Až budu u PC kde můžu nastavit Travise, tak tento PR zamerguju a začnu pracovat na dalších issues, abychom mohli ubuntu.cz co nejdříve nahradit.

2018-12-07 14:35 UTC, merged